name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: order-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest

      - name: Build Docker image
        run: docker build -t order-service .

      - name: Run tests (optional second run)
        env:
          PYTHONPATH: .
        run: pytest